name: CI

on: [
  workflow_call,
  workflow_dispatch
]

jobs:
  Test-Runner:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'tests: propactive-jvm'
        run: make test-propactive-jvm
      - name: 'tests: propactive-plugin (acceptance)'
        run: make test-acceptance-propactive-plugin
      - name: 'tests: propactive-plugin (integration)'
        run: make test-integration-propactive-plugin
      # TMP: #70 This should be removed once gradle-nexus/publish-plugin/issues/208 is fixed
      - name: 'A timebomb to address #70 on the 2023-12-01'
        run: |
          if [[ $(date +%s) -gt 1701388800 ]]; then
            echo "It has been many months since #70 was opened."
            echo "Please check if gradle-nexus/publish-plugin/issues/208 has been fixed."
            echo "  If it has, please update the plugin and re-enable the CD workflow."
            echo "  else, please increase this timebomb by 1 month."
            echo "See: propactive/propactive/issues/70"
            exit 1
          fi
      - name: 'Uploading test artifacts'
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ./*/build/test-results/test/*.xml
            ./*/build/reports
      - name: 'Running KtLinter'
        run: make check-linter

  Test-Reporter:
    needs: Test-Runner
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Downloading all artifacts'
        uses: actions/download-artifact@v3
      - name: 'Generating test report for Github actions'
        uses: dorny/test-reporter@v1.6.0
        with:
          name: 'Test Report: JUnit'
          path: ./test-artifacts/*/build/test-results/test/*.xml
          reporter: java-junit
      - name: 'Uploading propactive-jvm coverage results to CodeClimate'
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: "${{ github.workspace }}/propactive-jvm/src/main/kotlin"
        with:
          coverageLocations: ${{ github.workspace }}/test-artifacts/propactive-jvm/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
