name: REFRESH_VERSIONS

on: workflow_dispatch

jobs:
  "Refresh-Versions":
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
        with:
          ref: main
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: 'Checkout to a new branch'
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: dependency-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Running: refreshVersions'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: refreshVersions
      - name: 'Committing new changes'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: Refresh gradle.properties
          new_branch: dependency-update
          push: --force --set-upstream origin dependency-update
      - name: 'Create a PR with above changes'
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dependency-update
          destination_branch: main
          pr_title: Upgrade Project dependencies
          pr_body: '[refreshVersions](https://github.com/jmfayard/refreshVersions) has found those library updates!'
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
