# Docker provides a set of official GitHub Actions for us to use in our
# workflows to build and push images to Docker Hub and other registries.
#
# See: https://docs.docker.com/build/ci/github-actions/
name: Toolchain Deployment

on:
  push:
    branches:
      - main
    paths:
      - ./Dockerfile

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build_and_publish:
    runs-on: ubuntu-22.04

    steps:
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: propactive/runner:latest
